secrets:
  mysql_root_password:
    file: /etc/light/lamarche_db/mysql_root_password
  mysql_database:
    file: /etc/light/lamarche_db/mysql_database
  mysql_user:
    file: /etc/light/lamarche_db/mysql_user
  mysql_password:
    file: /etc/light/lamarche_db/mysql_password

services:
  lamarche_db:
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_password
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_DATABASE: /run/secrets/mysql_database
      MYSQL_USER: /run/secrets/mysql_user
      MYSQL_PASSWORD: /run/secrets/mysql_password
    volumes:
      - /var/lib/dbs/lamarche_db:/var/lib/mysql

  wordpress:
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
    environment:
      WORDPRESS_DB_HOST: lamarche_db
      WORDPRESS_DB_NAME: /run/secrets/mysql_database
      WORDPRESS_DB_USER: /run/secrets/mysql_user
      WORDPRESS_DB_PASSWORD: /run/secrets/mysql_password
      
    labels:
      # Domain
      - "traefik.http.routers.lamarchemeat.rule=Host(`lamarchemeat.com`, `www.lamarchemeat.com`)"
      # Cert Resolver
      - "traefik.http.routers.lamarchemeat.tls.certresolver=prodcertresolver"
